services:
  db:
    image: postgres:15
    container_name: blurrt-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anecdotes
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: blurrt-backend-prod
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: blurrt-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
